### ISSUE TITLE
Feature: Add Search bar for sensors

### ISSUE THREAD

**Issue by Brazier85** [gensyn/de_gensyn_HomeAssistantPlugin#12]
Hello,
when I want to select a sensor in your plugin, there is a really long list I have to search. Is it possible to add a search bar or maybe add a second field where I can type in the sensor manually? That would really make it much simpler.

Currently I use the .json and add my entries manually.

**Comment by gensyn** [comment]
I feel your pain but it's surprisingly complex to implement such a simple concept in Gtk 4.0. I'll take another look and maybe try to find example code.

**Comment by gensyn** [comment]
A text field to manually add a sensor would be Plan B.

**Comment by Brazier85** [comment]
Maybe you can use a [DropDown](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.DropDown.html). I never used GTK so I don*t how much afford it is to implement something like that

**Comment by gensyn** [comment]
Yeah, but the search functionality sadly doesn't come out of the box. You have to work with a factory and it's not trivial.

**Comment by gensyn** [comment]
Well, that was a very painful road, but I got it to work and I'm happy with the result. It should already be available in the StreamController-Store; could you give it a try and tell me if it works for you?

**Comment by Brazier85** [comment]
oh, wow! It is working great and makes it so much easier to configure the buttons.

Thank you!
