### ISSUE TITLE
Control Light Temperature

### ISSUE THREAD

**Issue by oparada1988** [gensyn/de_gensyn_HomeAssistantPlugin#14]
I use the elgato key light mini, on the webui i am able to control the light temp, but in the streamcontroller plugin in no, or perhaps, im not sure how.

**Comment by gensyn** [comment]
Under `call service` is a list of possible parameters for the service. If you want to change the light temperature I assume you need to use the light service `turn_on` and set the desired `color_temp`:

![image](https://github.com/user-attachments/assets/adb9f5b4-60cd-435a-8558-443387763324)

**Comment by oparada1988** [comment]
Ah, okay! Got ya! Thanks for this! Theres no way to do a "slider" sort of thing I assume?

**Comment by gensyn** [comment]
Currently not planned but I added it to the list of possible improvements.

**Comment by oparada1988** [comment]
thank you! closing :-)
