### ISSUE TITLE
Show unit of measurement selector

### ISSUE THREAD

**Issue by dfullaway** [gensyn/de_gensyn_HomeAssistantPlugin#15]
The "Show unit of measurement" selector is inactive for sensors that have a valid "unit_of_measurement" attribute. I can verify that the plugin can see the unit of measure by switching the entity text value to "unit_of_measurement". 

I'm currently using SteamController version 1.5.0-beta.6. 
Plugin version is 0.9.3-beta.

**Comment by gensyn** [comment]
Ok, the fix should now be available in the Store. Could you please verify?

**Comment by gensyn** [comment]
I assume everything is fine now.
