### ISSUE TITLE
Feature Request: Support for Custom Icons Based on Entity States

### ISSUE THREAD

**Issue by SeitHali** [gensyn/de_gensyn_HomeAssistantPlugin#16]
Would it be possible to add support for custom icons that change based on an entity’s state?

**Comment by gensyn** [comment]
I have plans to add support of custom icon and text color, and it should be possible to add custom icons the same way.

**Comment by gensyn** [comment]
There's a new version available in the store where you can define custom icons. Feel free to try it out and give me feedback.

**Comment by gensyn** [comment]
Seems to be working. I'm closing this issue.
