### ISSUE TITLE
Support for person entities

### ISSUE THREAD

**Issue by zeridon** [gensyn/de_gensyn_HomeAssistantPlugin#19]
I am using the plugin in order to display a mini dashboard including few person entities. Home assistant the person to be `home` and `not_home` which map to the `on` and `off` state of a lightbulb for example.

The below referenced code is setting the on/off state for the icon, but does not support the person entity (`home` state)

https://github.com/gensyn/de_gensyn_HomeAssistantPlugin/blob/main/actions/HomeAssistantAction/home_asistant_action.py#L985

Please add support for `home` to be considered equivalent to `on`

**Comment by gensyn** [comment]
Sure. That makes sense and is easy enough to implement.
In fact, I already pushed the change and am currently waiting for approval from the StreamController-Store.

**Comment by gensyn** [comment]
The update is now available in the Store. Could you trying it out?

**Comment by zeridon** [comment]
thanks works :)
