### ISSUE TITLE
[Feature] Add extra params to the calls

### ISSUE THREAD

**Issue by lupus2k** [gensyn/de_gensyn_HomeAssistantPlugin#2]
Can we add different params like brightness or effect to the light calls?

For example:
```
{
    "entity_id": "light.ofi", 
    "rgb_color": [
        135,
        5,
        255
    ]
}
```

**Comment by gensyn** [comment]
It's possible to do that, yes. But it would require a textfield to input arbitrary JSON data and it would be the users responsibility to make sure that it has the correct format. Might be easier and more fool-proof to create a script in HomeAssistant and call the script from StreamController.

**Comment by gensyn** [comment]
I think I found a way to automatically make parameters available for each service, so this might come in a future release after all.

**Comment by gensyn** [comment]
This feature should be live now. Let me know, what you think
