### ISSUE TITLE
Use display precision from home assistant

### ISSUE THREAD

**Issue by asmaps** [gensyn/de_gensyn_HomeAssistantPlugin#23]
My energy meter spits out it's values with a lot of accuracy. For simple displaying 1 or 2 places after the dot are enough, so in HA I have set the display precision to show `436.4W` instaead of `436.43927834W`. When displaying on the streamdeck I get the full accuracy. Is there any possibility to either also set the accuracy in StreamController or just use the display accuracy from home assistant?

**Comment by gensyn** [comment]
Ok, I added the option to round values - the update is already available from the store. Feel free to test it and give me feedback.

**Comment by asmaps** [comment]
Thanks a lot. Unfortunately it doesn't seem to have any effect for me:

![Screenshot from 2024-11-20 16-07-40](https://github.com/user-attachments/assets/8214d781-cd9f-4b64-b4ae-cd9b93cc066b)

![image](https://github.com/user-attachments/assets/fca29a58-8b31-449d-a6b3-e0cda5b6f8ce)

**Comment by asmaps** [comment]
Ah I just noticed that it's only not working when showing the unit. If I hide it it works.

**Comment by gensyn** [comment]
Damn, I didn't test with unit. Will have a look tomorrow.

**Comment by gensyn** [comment]
A fix is now available from the store - please try again.

**Comment by asmaps** [comment]
Works, thank you very much!
