### ISSUE TITLE
Volume down icon don't show up

### ISSUE THREAD

**Issue by Vaarlion** [gensyn/de_gensyn_HomeAssistantPlugin#3]
Hello :)

I'm trying out this plugin and i'm very happy to see so much work already.
Little thing i found, A media_player volume_down service don't show the volume - icon.

I don't know what is your icon source, but i'm guessing the icon name might be wrong here ?

https://github.com/gensyn/de_gensyn_HomeAssistantPlugin/blob/932d73cdaed5b2027eb39b44cf1cefe50e2576f6/actions/HomeAssistantAction/HomeAssistantAction.py#L618C1-L619C43

**Comment by gensyn** [comment]
Yeah, there is a mistake in the current release which I already fixed in the code. I'm waiting for the next release of StreamController to drop for my next release because it depends on some changes. I hope this will be in the next couple of days.

**Comment by Vaarlion** [comment]
Ok, sorry.

The git blame on that line was 2 week old and spoke about key hold so i didn't bother checking if it was a fix for this.
I should have :)

**Comment by gensyn** [comment]
With the new version released today it should work. Could you please check?

**Comment by Vaarlion** [comment]
The icon show up correctly :)
Thank you
