### ISSUE TITLE
Show Entity Icon not working

### ISSUE THREAD

**Issue by ImDevinC** [gensyn/de_gensyn_HomeAssistantPlugin#9]
I've tried enabling the "Show Entity Icon" option for both a fan and a light, but I get no icon on my Streamdeck. Am I misunderstanding how this setting is used? I'm expecting to to provide the default icon that Home Assistant uses as the icon in Streamdeck

**Comment by gensyn** [comment]
I provide no default icons and I'm not aware that Home Assistant exposes them through the websockets API. So if the entity has no icon, nothing is shown.

**Comment by ImDevinC** [comment]
![image](https://github.com/gensyn/de_gensyn_HomeAssistantPlugin/assets/3997333/65d829f7-c747-4536-9455-ad2bb420f0fc)
To clarify, there are icons for these entities in Home Assistant that I'm seeing here. Are you saying you don't pull these icons? If so, how is the "Show Entity Icon" setting supposed to be used?

**Comment by gensyn** [comment]
Ah, no. If an icon is set, it should show up. Did you allow the action to set the button image in the action list?

**Comment by ImDevinC** [comment]
Not sure what you mean. I have a single action, "Home Assistant" that toggles the light and I have the "Show entity icon" enabled. I do know that the connection is working because if I enable the "Show entity state" option, I can see the text output of the state

![image](https://github.com/gensyn/de_gensyn_HomeAssistantPlugin/assets/3997333/678b6e2e-ffa2-4ddd-b8e3-b9a859f7d1fb)

**Comment by gensyn** [comment]
I cant take a screenshot right now, but in the list of the actions for the button (before you click on the Home Assistant action), you can set permissions for each action. But maybe you only see those with more than one action...? Could you try to add a second action? Then you should see permission buttons in each action where you can en- and disable image and label permissions. Make sure that the action is allowed to set the image.

**Comment by ImDevinC** [comment]
Ahh, do you mean this here?
![image](https://github.com/gensyn/de_gensyn_HomeAssistantPlugin/assets/3997333/34e462bd-0846-4c88-9806-1ec1e6fd3a2d)
I have tried with these settings toggled in all available options (image enabled:text disabled, image enabled:text enabled, image disabled:text enabled, image disabled:text disabled) with no change in behavior

**Comment by gensyn** [comment]
Yeah that.
That's weird. I had no issues so far. But I have a pull request to the Store pending for a new version. Maybe try again when that is merged before I go trouble shooting.

**Comment by ImDevinC** [comment]
Solved as a misunderstanding on my part. In HomeAssistant, you have to specify the icon you want to use on the entity, it will not pick up the default icon for the entity type. Thanks for the help!

**Comment by gensyn** [comment]
I just implemented that you can't enable "Show entity icon" if the entity has no icon. Hopefully that prevents further confusion.

**Comment by SteveGoodenough** [comment]
was about to raise the same issue and glad I looked at closed issues. Did you implement that "cannot enable show icon" as I was able to enable it but the solution above to specifically select an icon in HA was the fix for me. e.g. on the entity it said mdi:lightbulb but I had to choose an icon and select the same name and save it and then it appeared on the StreamDeck

**Comment by gensyn** [comment]
Yeah, that was implemented months ago and as far as I can tell it is working reliably. What version of the plugin are you using?
